export const bossData = {
  bosses: [
    {
      name: "Herszt",
      iconSrc: "https://wiki.taern.pl/images//b/ba/Herszt.jpg",
      taernWikiUrl: "https://wiki.taern.pl/index.php?title=Herszt",
      items: [
        {
          name: "Derengil",
          taernWikiUrl: "https://wiki.taern.pl/images//0/0e/Derengil.jpg",
          ranga: 5,
          cenaRynkowaMin: 100000,
          cenaRynkowaMax: 200000,
          dodatkowyOpis:
            "Ponieważ Herszt nie dropi epików, a rary z niego dają mało esencji, farmią go tylko nieliczni gracze. Dlatego mimo iż rary są bardzo tanie, trudno spotkać je na czacie handlowym.",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "sold",
              wytrzymalosc: 45,
              iloscGwiazdek: -1,
              cena: 150000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Maiarot",
          taernWikiUrl: "https://wiki.taern.pl/images//e/e0/Maiarot.jpg",
          ranga: 4,
          cenaRynkowaMin: 70000,
          cenaRynkowaMax: 70000,
          dodatkowyOpis:
            "Ponieważ Herszt nie dropi epików, a rary z niego dają mało esencji, farmią go tylko nieliczni gracze. Dlatego mimo iż rary są bardzo tanie, trudno spotkać je na czacie handlowym.",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "sold",
              wytrzymalosc: 41,
              iloscGwiazdek: -1,
              cena: 70000,
              dodatkoweInfo: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Sturprang",
          taernWikiUrl: "https://wiki.taern.pl/images//5/59/Sturprang.jpg",
          ranga: 4,
          cenaRynkowaMin: 20000,
          cenaRynkowaMax: 30000,
          dodatkowyOpis:
            "Ponieważ Herszt nie dropi epików, a rary z niego dają mało esencji, farmią go tylko nieliczni gracze. Dlatego mimo iż rary są bardzo tanie, trudno spotkać je na czacie handlowym.",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "sold",
              wytrzymalosc: 46,
              iloscGwiazdek: -1,
              cena: 25000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
      ],
    },
    {
      name: "Krzyżak",
      iconSrc: "https://wiki.taern.pl/images//4/40/Krzy%C5%BCak.jpg",
      taernWikiUrl: "https://wiki.taern.pl/index.php?title=Krzy%C5%BCak",
      items: [
        {
          name: "Martumal",
          taernWikiUrl: "https://wiki.taern.pl/images//4/4b/Martumal.jpg",
          ranga: 5,
          cenaRynkowaMin: 100000,
          cenaRynkowaMax: 150000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "bought",
              wytrzymalosc: 45,
              iloscGwiazdek: -1,
              cena: 100000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Arcanescape II",
          taernWikiUrl: "https://wiki.taern.pl/images//d/de/Arcanscape.jpg",
          ranga: 6,
          cenaRynkowaMin: 350000,
          cenaRynkowaMax: 500000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "sold",
              wytrzymalosc: 40,
              iloscGwiazdek: -1,
              cena: 400000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Ayol",
          taernWikiUrl: "https://wiki.taern.pl/images//a/a9/Ayol.jpg",
          ranga: 5,
          cenaRynkowaMin: 20000,
          cenaRynkowaMax: 30000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "sold",
              wytrzymalosc: 38,
              iloscGwiazdek: -1,
              cena: 25000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
      ],
    },
    {
      name: "Ichtion",
      iconSrc: "https://wiki.taern.pl/images//5/51/Ichtion.jpg",
      taernWikiUrl: "https://wiki.taern.pl/index.php?title=Ichtion",
      items: [
        {
          name: "Czengsvesy",
          taernWikiUrl: "https://wiki.taern.pl/images//a/a8/Czengsvesy.jpg",
          ranga: 5,
          cenaRynkowaMin: 100000,
          cenaRynkowaMax: 200000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "luty 2021",
              transactionType: "sold",
              wytrzymalosc: 45,
              iloscGwiazdek: -1,
              cena: 150000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Fiskorl II",
          taernWikiUrl: "https://wiki.taern.pl/images//7/71/Fiskorl.jpg",
          ranga: 6,
          cenaRynkowaMin: 250000,
          cenaRynkowaMax: 300000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              transactionType: "sold",
              wytrzymalosc: 45,
              iloscGwiazdek: -1,
              cena: 250000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Rolrak",
          taernWikiUrl: "https://wiki.taern.pl/images//a/a7/Rolrak.jpg",
          ranga: 5,
          cenaRynkowaMin: 100000,
          cenaRynkowaMax: 200000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "luty 2021",
              transactionType: "bought",
              wytrzymalosc: 45,
              iloscGwiazdek: -1,
              cena: 120000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
      ],
    },
    {
      name: "Ropucha",
      iconSrc: "https://wiki.taern.pl/images//e/e5/Ropucha.jpg",
      taernWikiUrl: "https://wiki.taern.pl/index.php?title=Ropucha",
      items: [
        {
          name: "Grzebień",
          taernWikiUrl: "https://wiki.taern.pl/images//7/72/Grzebie%C5%84.jpg",
          ranga: 5,
          cenaRynkowaMin: 150000,
          cenaRynkowaMax: 250000,
          dodatkowyOpis: "",
          historiaTransakcji: [],
        },
        {
          name: "Basileus",
          taernWikiUrl: "https://wiki.taern.pl/images//f/fe/Basileus.jpg",
          ranga: 6,
          cenaRynkowaMin: 300000,
          cenaRynkowaMax: 450000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "styczeń 2021",
              wytrzymalosc: 48,
              iloscGwiazdek: -1,
              cena: 300000,
              dodatkoweInfoOTransakcji: "",
            },
          ],
        },
        {
          name: "Moczary",
          taernWikiUrl: "https://wiki.taern.pl/images//f/f0/Moczary.jpg",
          ranga: 6,
          cenaRynkowaMin: 1000000,
          cenaRynkowaMax: 1500000,
          dodatkowyOpis: "",
          historiaTransakcji: [],
        },
        {
          name: "Fraxy",
          taernWikiUrl: "https://wiki.taern.pl/images//1/16/Fraxy.jpg",
          ranga: 6,
          cenaRynkowaMin: 1000000,
          cenaRynkowaMax: 1500000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "luty 2021",
              wytrzymalosc: 41,
              iloscGwiazdek: -1,
              cena: 1200000,
              dodatkoweInfoOTransakcji: "",
            },
          ],
        },
      ],
    },
    {
      name: "Konstrukt v.1",
      iconSrc: "https://wiki.taern.pl/images//d/d3/Konstrukt.jpg",
      taernWikiUrl: "https://wiki.taern.pl/index.php?title=Konstrukt_v.1",
      items: [
        {
          name: "Tangary",
          taernWikiUrl: "https://wiki.taern.pl/images//f/f4/Tangnary.jpg",
          ranga: 7,
          cenaRynkowaMin: 500000,
          cenaRynkowaMax: 2000000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "marzec 2021",
              transactionType: "sold",
              wytrzymalosc: 45,
              iloscGwiazdek: 4,
              cena: 1000000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Danthum",
          taernWikiUrl: "https://wiki.taern.pl/images//e/e4/Danthum.jpg",
          ranga: 7,
          cenaRynkowaMin: 500000,
          cenaRynkowaMax: 2000000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "marzec 2021",
              transactionType: "sold",
              wytrzymalosc: 42,
              iloscGwiazdek: 3,
              cena: 800000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
        {
          name: "Valazan",
          taernWikiUrl: "https://wiki.taern.pl/images//7/70/Valazan.jpg",
          ranga: 7,
          cenaRynkowaMin: 500000,
          cenaRynkowaMax: 2000000,
          dodatkowyOpis: "",
          historiaTransakcji: [
            {
              data: "marzec 2021",
              transactionType: "bought",
              wytrzymalosc: 50,
              iloscGwiazdek: 5,
              cena: 2000000,
              dodatkoweInfoOTransakcji: "Przykładowa transakcja.",
            },
          ],
        },
      ],
    },
  ],
};
export const essencesData = {
  essencesInfo: [
    [
      1,
      {
        ranga: 1,
        esencjeBezInhibitora: 1,
        esencjeZInhibitorem: 1,
        optymalnyInhib: "turkusowy",
        kosztInhibitoraPl: 3,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 15000,
      },
    ],
    [
      2,
      {
        ranga: 2,
        esencjeBezInhibitora: 1,
        esencjeZInhibitorem: 1,
        optymalnyInhib: "turkusowy",
        kosztInhibitoraPl: 3,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 15000,
      },
    ],
    [
      3,
      {
        ranga: 3,
        esencjeBezInhibitora: 1,
        esencjeZInhibitorem: 1,
        optymalnyInhib: "turkusowy",
        kosztInhibitoraPl: 3,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 15000,
      },
    ],
    [
      4,
      {
        ranga: 4,
        esencjeBezInhibitora: 1,
        esencjeZInhibitorem: 1,
        optymalnyInhib: "turkusowy",
        kosztInhibitoraPl: 3,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 15000,
      },
    ],
    [
      5,
      {
        ranga: 5,
        esencjeBezInhibitora: 4,
        esencjeZInhibitorem: 6,
        optymalnyInhib: "kwarcowy",
        kosztInhibitoraPl: 4,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 20000,
      },
    ],
    [
      6,
      {
        ranga: 6,
        esencjeBezInhibitora: 8,
        esencjeZInhibitorem: 11,
        optymalnyInhib: "kwarcowy",
        kosztInhibitoraPl: 4,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 20000,
      },
    ],
    [
      7,
      {
        ranga: 7,
        esencjeBezInhibitora: 15,
        esencjeZInhibitorem: 20,
        optymalnyInhib: "topazowy",
        kosztInhibitoraPl: 5,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 30000,
      },
    ],
    [
      8,
      {
        ranga: 8,
        esencjeBezInhibitora: 30,
        esencjeZInhibitorem: 39,
        optymalnyInhib: "korundowy",
        kosztInhibitoraPl: 6,
        czyKraftowalny: true,
        kosztInhibitoraKraft: 50000,
      },
    ],
    [
      9,
      {
        ranga: 9,
        esencjeBezInhibitora: 40,
        esencjeZInhibitorem: 52,
        optymalnyInhib: "szmaragdowy",
        kosztInhibitoraPl: 7,
        czyKraftowalny: false,
        kosztInhibitoraKraft: -1,
      },
    ],
    [
      10,
      {
        ranga: 10,
        esencjeBezInhibitora: 55,
        esencjeZInhibitorem: 72,
        optymalnyInhib: "diamentowy",
        kosztInhibitoraPl: 8,
        czyKraftowalny: false,
        kosztInhibitoraKraft: -1,
      },
    ],
    [
      11,
      {
        ranga: 11,
        esencjeBezInhibitora: 80,
        esencjeZInhibitorem: 104,
        optymalnyInhib: "andilunirowy",
        kosztInhibitoraPl: 10,
        czyKraftowalny: false,
        kosztInhibitoraKraft: -1,
      },
    ],
    [
      12,
      {
        ranga: 12,
        esencjeBezInhibitora: 120,
        esencjeZInhibitorem: 156,
        optymalnyInhib: "platynowy",
        kosztInhibitoraPl: 12,
        czyKraftowalny: false,
        kosztInhibitoraKraft: -1,
      },
    ],
  ],
};

export const starsItemsData = {
  starsItems: [
    "Tangary",
    "Danthum",
    "Valazan",
    "Powrót Ivravula",
    "Zemsta Ivravula",
    "Nadzieja Pokoleń",
    "Urntsul",
    "Sigil",
    "Harttraum",
    "Smuga",
    "Otwieracz",
    "Serce Seleny",
    "Groza Seleny",
    "Hańba Seleny",
    "Erbaile",
    "Alendry",
    "Przysięga Draugula",
    "Zagłada Ludów",
  ],
};
